sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "8"

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_script:
- npm install -g @angular/cli

script:
- npm run test-ci
- npm run build
- npm run build-lib

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/bootstrap
  provider: npm
  email: "robert.hjalmers@seb.se"
  api_key: $NPM_TOKEN
  local-dir: dist/lib
  on:
    branch: master
    tags: true
