dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js: node

install:
- npm run add-fa-config
- npm ci
cache:
  directories:
  - $HOME/.npm

script:
- npm run test-ci
- npm run build && npm run build-lib
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- npm run e2e-ci

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/bootstrap
    on:
      all_branches: true

git:
  depth: 3

after_success:
- npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
