dist: trusty
sudo: false
addons:
  chrome: beta
language: node_js
node_js: lts/*

install:
- npm run add-fa-config
- npm ci
cache:
  directories:
  - $HOME/.npm

script:
- npm run test-ci
- if [ "$TRAVIS_BRANCH" == "master" ];
  then npm run build && npm run build-lib && npm run build-sdl;
  else npm run build-dev && npm run build-lib;
  fi
- export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
- npm run e2e-ci

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/bootstrap
    on:
      branch: master

git:
  depth: 3

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ];
  then npm run travis-deploy-once "npm run semantic-release";
  fi


branches:
  except:
  - /^v\d+\.\d+\.\d+$/
